# Configuration file for portfolio website

# LinkedIn profile URL
linkedin_url: "https://www.linkedin.com/in/rogert-guevara-uzcategui"

# Profile picture URL
profile_picture_url: "https://media.licdn.com/dms/image/v2/D4D03AQFEY-pULJLzTg/profile-displayphoto-crop_800_800/profile-displayphoto-crop_800_800/0/1734132057595"

# Contact email
email: "inforogert@gmail.com"

# Personal information
name: "Rogert Guevara Uzcátegui"
title: "Network & Systems Administrator"
location: "Palma, Balearic Islands, Spain"