# Configuration file for portfolio website

# LinkedIn profile URL
linkedin_url: "https://www.linkedin.com/in/rogert-guevara-uzcategui"

# Profile picture URL
profile_picture_url: "img/profile.jpg"

# Contact email
email: "inforogert@gmail.com"

# Personal information
name: "Rogert Guevara Uzcátegui"
title: "Network & Systems Administrator"
location: "Palma, Balearic Islands, Spain"